### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by WardLootens** [blachniet/dotfiles-windows#1]
Hello,

I like your [stow](https://github.com/blachniet/dotfiles-windows/blob/master/stow.ps1) script. It's simple, and perfectly matches my needs to manage my dotfiles.
Would it be okay if I'd use a copy of the script in my dotfiles repository?

Ward

**Comment by blachniet** [comment]
I'm glad you find it useful. I've added the MIT license. Enjoy!
